# This file is part of the BenGorUser package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    bengor.user.infrastructure.routing.symfony_url_generator:
        class: BenGorUser\SymfonyRoutingBridge\Infrastructure\Routing\SymfonyUserUrlGenerator
        public: false
        arguments:
            - '@router'
    bengor_user.symfony_url_generator:
        alias: bengor.user.infrastructure.routing.symfony_url_generator
